Lesson8 task2 geometric figures
Jelowpat/Pat_Jel_Maven_Java_project pull request #12
Opened 2023-07-08 13:36 UTC by Jelowpat

2023-07-11 08:54 UTC, patryk-stepniak requested changes

2023-07-11 08:54 UTC, patryk-stepniak commented on src/main/java/lessonEightGeometricFigures/Circle.java
> +    private static final double PI = Math.PI;
stałe umieszczajmy na samym początku ciała klasy - tak się przyjęło. Robienie inaczej nie jest błędem, ale wolę Ci o tym wspomnieć

2023-07-11 08:54 UTC, patryk-stepniak commented on src/test/java/lessonEightGeometricFigures/SquareTest.java
> +    Square square = new Square(5);
dlaczego domyślny zasięg?

2023-07-12 12:24 UTC, Jelowpat commented on src/main/java/lessonEightGeometricFigures/Circle.java
> +    private static final double PI = Math.PI;
poprawiono :)

2023-07-12 12:24 UTC, Jelowpat commented on src/main/java/lessonEightGeometricFigures/Rectangle.java
> +    double sideA;
poprawiono :)

2023-07-12 12:26 UTC, Jelowpat commented on src/test/java/lessonEightGeometricFigures/SquareTest.java
> +    Square square = new Square(5);
poprawiono :)

2023-07-12 12:26 UTC, Jelowpat commented on src/main/java/lessonEightGeometricFigures/Triangle.java
> +    double sideA;
poprawiono :)

2023-07-13 15:53 UTC, merged