Lesson8 task3 area and perimeter
Jelowpat/Pat_Jel_Maven_Java_project pull request #13
Opened 2023-07-10 16:01 UTC by Jelowpat

2023-07-11 08:56 UTC, patryk-stepniak requested changes

2023-07-11 08:56 UTC, patryk-stepniak commented on src/test/java/lessonEightAreaAndPerimeter/CircleTest.java
> +    Circle circle = new Circle(7);
zagięg

2023-07-11 08:56 UTC, patryk-stepniak commented on src/test/java/lessonEightAreaAndPerimeter/SquareTest.java
> +    Square square = new Square(8);
zagięg

2023-07-12 12:32 UTC, Jelowpat commented on src/test/java/lessonEightAreaAndPerimeter/CircleTest.java
> +    Circle circle = new Circle(7);
poprawione :)

2023-07-13 15:54 UTC, patryk-stepniak approved these changes

2023-07-13 15:54 UTC, merged