completed task5
Jelowpat/Pat_Jel_Maven_Java_project pull request #15
Opened 2023-07-10 16:26 UTC by Jelowpat

2023-07-11 09:00 UTC, patryk-stepniak requested changes

2023-07-11 09:00 UTC, patryk-stepniak commented on src/main/java/lesson8Animal/Animal.java
> +    String name;
dlaczego zasięg domyslny?

2023-07-12 12:44 UTC, Jelowpat commented on src/main/java/lesson8Animal/Animal.java
> +    String name;
poprawione :)

2023-07-13 15:58 UTC, patryk-stepniak approved these changes

2023-07-13 15:58 UTC, merged