created enum WeekDay and class DayOfTheWeek, using enum Weekday, crea…
Jelowpat/Pat_Jel_Maven_Java_project pull request #17
Opened 2023-07-10 17:07 UTC by Jelowpat

created enum WeekDay and class DayOfTheWeek, using enum Weekday, created a test

2023-07-11 09:04 UTC, patryk-stepniak requested changes

2023-07-11 09:04 UTC, patryk-stepniak commented on src/main/java/lesson8WeekDaysNames/WeekDay.java
> +    Monday("Monday"),
Rzuć okiem na metodę "name()" należącej go każdego enuma :)

2023-07-11 09:04 UTC, patryk-stepniak commented on src/main/java/lesson8WeekDaysNames/DayOfTheWeek.java
> +    public static String whatDayIsIt(WeekDay day) {
Niepoprawna nazwa metody.

Metoda zwraca nazwę dnia tygodnia, więc zapiszmy to jako "getDayName" lub jakoś podobnie.

2023-07-11 09:04 UTC, patryk-stepniak commented on src/test/java/lesson8WeekDaysNames/DayOfTheWeekTest.java
> +        Assertions.assertEquals("Monday", DayOfTheWeek.whatDayIsIt(WeekDay.Monday));
Tylko jeden test? ;>

2023-07-12 12:53 UTC, Jelowpat commented on src/main/java/lesson8WeekDaysNames/WeekDay.java
> +    Monday("Monday"),
uzylem "name()" ale zostawilem te funkcjonalnosc, zamiast nazw, teraz te obiety trzymaja numer dnia tygodnia

2023-07-14 14:13 UTC, Jelowpat commented on src/main/java/lesson8WeekDaysNames/WeekDay.java
> +    private final int DayNumber;
wyrzuciłem tę funkcjonalność

2023-07-14 14:13 UTC, Jelowpat commented on src/main/java/lesson8WeekDaysNames/WeekDay.java
> +    private final int DayNumber;
wyrzuciłem tę funkcjonalność

2023-07-14 14:20 UTC, Jelowpat commented on src/test/java/lesson8WeekDaysNames/DayOfTheWeekTest.java
> +        Assertions.assertEquals("Monday", DayOfTheWeek.whatDayIsIt(WeekDay.Monday));
dodałem testy

2023-07-24 07:13 UTC, patryk-stepniak approved these changes

2023-07-24 07:14 UTC, merged