Lesson6 task4 age verification
Jelowpat/Pat_Jel_Maven_Java_project pull request #2
Opened 2023-07-03 13:18 UTC by Jelowpat

2023-07-04 17:07 UTC, patryk-stepniak requested changes

2023-07-04 17:07 UTC, patryk-stepniak commented on src/main/java/lessonSixAgeVerification/AgeVerification.java
> +    public static boolean verifyingAge(int a){
Nazwa metody nie jest czasownikiem.
Nazwa argumentu nic nam nie mówi.

2023-07-04 17:07 UTC, patryk-stepniak commented on src/test/java/lessonSixAgeVerification/AgeVerificationTest.java
> +    public void isPositivelyVerified() {
Nazwy testów zaczynamy od "should".

2023-07-04 20:11 UTC, Jelowpat commented on src/main/java/lessonSixAgeVerification/AgeVerification.java
> +    public static boolean verifyingAge(int a){
veryfing tachnicznie jest czasownikiem ;) ale rozumiem ze chodzi o forme 'verify'

2023-07-04 20:13 UTC, Jelowpat commented on src/main/java/lessonSixAgeVerification/AgeVerification.java
> +    public static boolean verifyingAge(int a){
zrobione

2023-07-04 20:13 UTC, Jelowpat commented on src/test/java/lessonSixAgeVerification/AgeVerificationTest.java
> +    public void isPositivelyVerified() {
zrobione

2023-07-11 08:33 UTC, patryk-stepniak approved these changes

2023-07-11 08:33 UTC, merged