Lesson6 task5 odd or even
Jelowpat/Pat_Jel_Maven_Java_project pull request #3
Opened 2023-07-03 13:18 UTC by Jelowpat

2023-07-04 17:10 UTC, patryk-stepniak requested changes

2023-07-04 17:10 UTC, patryk-stepniak commented on src/main/java/lessonSixOddOrEven/OddOrEven.java
> +    public static String CheckIfEvenOrOdd (int a){
W poleceniu była mowa o "metodach". Jedna powinna sprawdzać, czy wartość jest parzysta, a druga, czy jest niepatrzysta.

2023-07-04 19:36 UTC, Jelowpat commented on src/test/java/lessonSixOddOrEven/OddOrEvenTest.java
> +    public void isEven() {
a czy nie była mowa o tym że właśnie zaczynamy od 'should' lub 'is'?

2023-07-04 20:24 UTC, Jelowpat commented on src/main/java/lessonSixOddOrEven/OddOrEven.java
> +    public static String CheckIfEvenOrOdd (int a){
zrobione

2023-07-04 20:24 UTC, Jelowpat commented on src/main/java/lessonSixOddOrEven/OddOrEven.java
> +    public static String CheckIfEvenOrOdd (int a){
zrobione

2023-07-04 20:24 UTC, Jelowpat commented on src/test/java/lessonSixOddOrEven/OddOrEvenTest.java
> +    public void isEven() {
zrobione

2023-07-11 08:36 UTC, patryk-stepniak requested changes

2023-07-11 08:36 UTC, patryk-stepniak commented on src/test/java/lessonSixOddOrEven/OddOrEvenTest.java
> +class OddOrEvenTest {
Brakuje jeszcze dwóch testów ;>

Każda z metod może zwrócić dwa możliwe wyniki true lub false. Metody mamy dwie, a więc: ilość możliwych wyników razy ilość metod = 4 testy

2023-07-12 11:54 UTC, Jelowpat commented on src/test/java/lessonSixOddOrEven/OddOrEvenTest.java
> +class OddOrEvenTest {
dodane :)

2023-07-13 15:52 UTC, merged