createt SeasonChecker and tests
Jelowpat/Pat_Jel_Maven_Java_project pull request #37
Opened 2023-07-28 16:58 UTC by Jelowpat

2023-08-02 08:15 UTC, patryk-stepniak requested changes

2023-08-02 08:15 UTC, patryk-stepniak commented on src/main/java/lesson11Season/Season.java
> +    winter,
Lepiej będzie jak wartości zapiszesz wielkimi literami. Będą się bardziej wyróżniać w kodzie.

2023-08-02 08:15 UTC, patryk-stepniak commented on src/main/java/lesson11Season/SeasonChecker.java
> +            case JANUARY, FEBRUARY, MARCH -> Season.winter;
Użyj statycznych importów dla pór roku.

2023-08-02 20:47 UTC, Jelowpat commented on src/main/java/lesson11Season/Season.java
> +    winter,
done ;)

2023-08-02 20:47 UTC, Jelowpat commented on src/main/java/lesson11Season/SeasonChecker.java
> +            case JANUARY, FEBRUARY, MARCH -> Season.winter;
done ;)

2023-08-08 07:54 UTC, DamianMarek98 approved these changes

2023-08-10 17:37 UTC, merged