Lesson11 task2 capital letters
Jelowpat/Pat_Jel_Maven_Java_project pull request #38
Opened 2023-07-28 17:37 UTC by Jelowpat

2023-08-02 08:17 UTC, patryk-stepniak requested changes

2023-08-02 08:17 UTC, patryk-stepniak commented on src/main/java/lesson11CapitalLetters/CapitalLetters.java
> +            throw new IllegalArgumentException();
Przydała by się jakaś wiadomość. Sam wyjątek niewiele nam powie.

2023-08-02 20:43 UTC, Jelowpat commented on src/main/java/lesson11CapitalLetters/CapitalLetters.java
> +            throw new IllegalArgumentException();
poprawione ;)

2023-08-08 07:51 UTC, DamianMarek98 approved these changes

2023-08-10 17:37 UTC, merged