implemented OwList with MyList
Jelowpat/Pat_Jel_Maven_Java_project pull request #43
Opened 2023-07-30 22:40 UTC by Jelowpat

2023-08-15 13:45 UTC, DamianMarek98 requested changes
Warto byłoby żebyś dodał testy, aby uniknąć podobnych błędów jak w metodzie add(int index, Integer element)

2023-08-15 13:45 UTC, DamianMarek98 commented on src/main/java/lesson12MyList/MyList.java
> +        System.arraycopy(content, index,
Przed wywołaniem arraycopy brakuje poszerzenia tablicy, wywołanie tej metody powoduje błąd. 
Należy dodać przed System,arraycopy(...) linię:
`content = Arrays.copyOf(content, size + 1);`

2023-08-15 13:45 UTC, DamianMarek98 commented on src/main/java/lesson12MyList/MyList.java
> +    private int size = 0;
skoro tablica jest zawsze zainicjowana możesz rozważyć wykorzystanie content.length zamiast samemu zajmować się zmienną size.

2023-08-25 10:25 UTC, marwis1995 approved these changes

2023-08-25 10:25 UTC, merged