added phonebook operating on phonebook positoon
Jelowpat/Pat_Jel_Maven_Java_project pull request #45
Opened 2023-08-11 20:32 UTC by Jelowpat

2023-08-13 07:01 UTC, patryk-stepniak requested changes

2023-08-13 07:01 UTC, patryk-stepniak commented on src/main/java/lesson14PhoneBook/main.java
> +public class main {
z małej litery?

2023-08-13 10:31 UTC, Jelowpat commented on src/main/java/lesson14PhoneBook/PhoneBook.java
> +        phoneBook.put(position.getName()+" "+position.getSurname(), position);
w jaki sposob wtedy uzywac obiektu tej klasy do szukania po kluczu, skoro bedzie miala dwa pola? nie rozumiem jak to zaaplikowac

2023-08-13 10:32 UTC, Jelowpat commented on src/main/java/lesson14PhoneBook/PhoneBook.java
> +    public void addPositionsFromFile(Path path) throws IOException {
jak to połączyć z pomysłem prywatnej klasy 'Entry' dla PhoneBooku?

2023-08-25 10:55 UTC, marwis1995 approved these changes

2023-08-25 10:55 UTC, merged