added class Film and its attributes
Jelowpat/Pat_Jel_Maven_Java_project pull request #6
Opened 2023-07-04 21:00 UTC by Jelowpat

2023-07-11 08:39 UTC, patryk-stepniak requested changes

2023-07-11 08:39 UTC, patryk-stepniak commented on src/test/java/FirstPackage/FirstClassTest.java
> +class FirstClassTest
Ta klasa jest pusta, a co za tym idzie -> jest nam niepotrzebna ;)

2023-07-11 08:39 UTC, patryk-stepniak commented on src/test/java/FirstPackage/FirstClassTest.java
> +class FirstClassTest
Swoją drogą nazwa tego pliku jest niepoprawna ;>

2023-07-12 11:58 UTC, Jelowpat commented on src/test/java/FirstPackage/FirstClassTest.java
> +class FirstClassTest
ta klasa została utworzona w masterze i pojawia się na wszystkich branchach, nie bardzo wiem jak ją wszędzie usunąć gdy sa pull requesty otwarte

2023-07-14 14:05 UTC, Jelowpat commented on src/test/java/FirstPackage/FirstClassTest.java
> +class FirstClassTest
poprawione swoją drogą :)

2023-07-23 19:10 UTC, patryk-stepniak approved these changes

2023-07-23 19:10 UTC, merged